#!/bin/bash

echo "================================"
echo "Sandbox Purchase Cleanup Guide"
echo "================================"
echo ""
echo "The 'duplicate purchase' errors suggest you have existing sandbox subscriptions."
echo ""
echo "To clear sandbox purchases:"
echo ""
echo "1. On your test device/simulator:"
echo "   - Go to Settings > App Store"
echo "   - Sign out of sandbox account"
echo "   - Sign back in with sandbox account"
echo ""
echo "2. Alternative - Reset all subscriptions:"
echo "   - Go to App Store Connect"
echo "   - Navigate to Users and Access > Sandbox Testers"
echo "   - Edit your sandbox tester"
echo "   - Click 'Clear Purchase History'"
echo ""
echo "3. Or create a new sandbox tester:"
echo "   - In App Store Connect"
echo "   - Users and Access > Sandbox Testers"
echo "   - Click '+' to add new tester"
echo "   - Use the new account for testing"
echo ""
echo "4. For simulator testing:"
echo "   - Device > Erase All Content and Settings"
echo "   - This will clear all sandbox data"
echo ""
echo "After clearing, the paywall should work properly."
echo ""
echo "Current error in logs:"
echo "ASDErrorDomain Code=825 'No transactions in response'"
echo "This typically means the sandbox account already owns the product."